name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Successful
        run: echo "Website Build Successful"

      - name: Deployment Successful
        run: echo "Website Deployed Successfully"
